# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagewithicon',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='pagewithicon',
            name='richtextpage_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.RichTextPage'),
            preserve_default=False,
        ),
    ]
