# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('metro', '0004_auto_20160724_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagewithicon',
            name='richtextpage_ptr',
        ),
        migrations.AddField(
            model_name='pagewithicon',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagewithicon',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagewithicon',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='icon'),
        ),
    ]
