# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0005_auto_20160724_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagewithicon',
            name='menustyle',
            field=models.CharField(default='green', max_length=255, verbose_name='menustyle'),
            preserve_default=False,
        ),
    ]
