# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('photologue', '0010_auto_20160105_1307'),
        ('metro', '0006_pagewithicon_menustyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('icon', models.CharField(max_length=255, verbose_name='icon')),
                ('menustyle', models.CharField(max_length=255, verbose_name='menustyle')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
