# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('metro', '0007_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photos',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photos',
            field=models.ManyToManyField(to='photologue.Gallery'),
        ),
    ]
